server {
    listen 80;
    server_name lingocoach.duckdns.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name lingocoach.duckdns.org;

    ssl_certificate     /etc/letsencrypt/live/lingocoach.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lingocoach.duckdns.org/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}